### ISSUE TITLE
VERSO step 2 inputs 

### ISSUE THREAD

**Issue by AndreaAguadoM** [BIMIB-DISCo/VERSO#4]
Hello. 

My name is Andrea Aguado and I am a bioinformatician currently woriking in viral quasispecies detection and further analysis. My problem resides in the VERSO step 2 inputs, since I do not know how they were obtained from the VERSO step 1 output file. I have been studying the output file obtained using the files given as example for the step 1 pipeline. I have been analyzing the output obtained from my own files as well. Still, i do not find the resemblance from this mentioned files and the required as inputs in step 2. Is there any code available in order to turn the verso step 1 output file in the required inputs or does it have to be self made?

Thanks in advance!

**Comment by DavideMaspero** [comment]
Dear Andrea, 

Yes, unfortunately, you have to prepare the input files by yourself. 
One of the outputs of VERSO step 1 is the Genotype ID assigned to each sample in your input file. This information is used in step 2 to process the minor variants grouped by the same "Corrected Clonal Genotype" independently from the others.
So you have to create three files as explained here https://github.com/BIMIB-DISCo/VERSO/tree/VERSO/VERSO_STEP_2 and run the python script.
Please, be aware of using the same file names we indicated in the instructions.

If you have any further questions, please let us know,

Best regards,
Davide Maspero

**Comment by AndreaAguadoM** [comment]
Dear Danielle

I am still struggling with the VERSO step 2 inputs. Specifically, this time
I got stuck on the sample_info_matrix.csv. Specifically, I do not
understand the meaning of the Attribute_1 and Attribute_2 columns, since i
do not understand which information they add to the table.

Thanks in advance!

**Comment by AndreaAguadoM** [comment]
About this same matrix:
Does the Column genotype refer to the inference$C VERSO step 1 output?
Thanks in advance again!
