### ISSUE TITLE
sample_info_matrix.csv 

### ISSUE THREAD

**Issue by AndreaAguadoM** [BIMIB-DISCo/VERSO#6]
Good morning 

I am still struggling with the VERSO step 2 inputs. Specifically, this time
I got stuck on the sample_info_matrix.csv. Specifically, I do not
understand the meaning of the Attribute_1 and Attribute_2 columns, since i
do not understand which information they add to the table. 

About this same matrix:
Does the Column genotype refer to the inference$C VERSO step 1 output?

Thanks in advance!

**Comment by DavideMaspero** [comment]
Dear Andrea, 

Attribute_1 and _2 refer to optional columns to store other sample metadata. 
The only two mandatory columns are "Genotype" and "Selected." The values in the former correspond to the genotype assignment, which you can easily obtain with a command like this
as.numeric(gsub(x=inference$C, pattern='G', replacement='')) 

The values of the second can all be 1 if all samples have been selected.

Best regards,
Davide Maspero
