### ISSUE TITLE
VF_matrix 

### ISSUE THREAD

**Issue by AndreaAguadoM** [BIMIB-DISCo/VERSO#7]
Good morning 

I am trying to use verso over 7 samples taken from the same patient over different days, since a rare SARS-CoV-2 viral infection was taking place within his organism. Thereby, the main aim of this VERSO application would be identifying low frequency viral variants so as to get more information than the one we already have about this infection over time. 

Specifically, when performing step 1, every sample was linked to a different genome, so the execution of VERSO step 2 was barely no sense, because no comparison of samples linked to the same genome could be done. So, i was thinking. From step 1 to step 2, our VF matrix was built using the information that we already had from vcf files, in order to fill the probability of every observed mutation in every sample so as to build the aforementioned matrix. Actually, this would have no sense since vcf files already contain the information about variation within every sample, but do not contain information about every possible virus variant within every sample (as a bam file does contain). So I was wondering, in the VERSO wiki VF_matrix given example, where does the probability  come from? We are very interested in the results that we could obtain using this tool, taking as reference what it is described in "VERSO: A comprehensive framework for the inference of robust phylogenies and the quantification of intra-host genomic diversity of viral samples", but we are a little bit lost when trying to perform all this workflow. 

Thanks in advance!

**Comment by danro9685** [comment]
Dear @AndreaAguadoM,

If I understand, you are trying to analyze heterogeneity for 1 single patients for which you have longitudinal data.

VERSO, and in particular STEP 1, was designed to perform phylogenetic inference from multiple samples (meaning coming from multiple patients). The output of STEP 1 is a set of "groups" that are further refined by STEP 2.

Given this, VERSO is not specifically designed for your setting.  You may try to force STEP 2 to use all samples by giving only 1 group as input, in this case you would have an estimate of the difference in minor mutations composition across the samples. But, this is not the optimal scenario the tool was defined for.

All the best,
Daniele
